### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by hobbypunk90**
Add bluepy and warrant.
Both can't build while starting, they needs the gcc and make. 
bluepy needs also glib.

### CODE REVIEW

**Comment by seblucas** [comment]
Hi,

Thanks for the PR !

You are the first one to propose a PR so I'm not ready yet (no travis enabled to check if your modification works, no way to check the image size change, etc).  So sorry in advance as there may be a delay before the merge :(

The thing that is the most disturbing for me is glib as it will make the image bigger ! Did you check by how much ?

Offtopic : last time I check you had to run your container with `--net host` to use bluetooth. At least that's the way I use it right now so I chose to isolate it in a dedicated container that share bluetooth information  through MQTT. I'm certainly paranoid but homeassistant is publised on the web so I don't want it on a the host network. How do you use bluetooth in your homeassistant image ?

Thanks again

**Comment by hobbypunk90** [comment]
No problem with the delay ;) i can also add a commit for the update to 0.63.3^^
The image is ~173MB large. 
And you are right, the `--net host` option is needed. But it is ok for me, because i don't want to use homeassistant over the internet^^

**Comment by seblucas** [comment]
First your PR works on armhf (I'll test it on arm64 tomorrow)

The image grew a lot:
 * Vanilla : 122MB
 * with only warrant : 168MB (+46MB)
 * your full PR : 173MB (+5MB)

I thought `glib` would be a problem and I'm wrong ;). I'll have to see if I can find any interest for me in HASS cloud offer (I guess that's the point of warrant) but for now I don't think I'll merge `warrant`, sorry.

**Comment by hobbypunk90** [comment]
I use it on a rpi3 ;) :D no problem without warrant, i added it because, it's not installable later and perhaps anybody else want to use it ;)

**Comment by seblucas** [comment]
Sorry but as you might have guessed I won't merge your PR because of its size impact.

**Pull request closed without merging**
